### ISSUE TITLE
Tracking standalone build feature request

### ISSUE THREAD

**Issue by jjsjann123** [NVIDIA/Fuser#101]
Currently we have remaining things to handle:

- [x] [**_HIGH PRIORITY_**] packaging libnvrtc for pip installation on system with no CUDA TK. We need this in order to support pip installed pytorch!!!! tackling in https://github.com/NVIDIA/Fuser/pull/176
- [x] remove gloo build from standalone build (we should only need its headers): [Discussion on PR](https://github.com/NVIDIA/Fuser/pull/59#discussion_r1152411318)
- [x] setuptools should provide options to enable debug build on standalone. #223
- [x] python setup.py install doesn't function properly. reported by @rdspring1 #153 
- [ ] runtime files gets regenerated even when no changes are applied. reported by @rdspring1 #152 
- [x] standalone build should install binaries on local folder. (CMAKE_INSTALL_PREFIX?!).
>Masaki runs into build failure where a bare metal build doesn't have access.
-- Up-to-date: /usr/local/include
CMake Error at third_party/googletest/googlemock/cmake_install.cmake:46 (file):
  file INSTALL cannot set permissions on "/usr/local/include": Operation not
  permitted.
Call Stack (most recent call first):
  third_party/googletest/cmake_install.cmake:47 (include)
  cmake_install.cmake:47 (include)
- [x] pip build seems to also be writing to global folders. reported by @t-vi https://github.com/NVIDIA/Fuser/pull/220#issuecomment-1522172170
- [ ] switch to setuptools_scm for versioning instead of using home brewed methods. Requested by @zasdfgbnm https://github.com/NVIDIA/Fuser/pull/161#issuecomment-1503905662

- [x] switch to lazyNVRTC on pytorch for driver&nvrtc calls, instead of linking directly against driver & nvrtc library. This may or may not be a necessary thing or good idea, if we want to ship nvfuser separate from pytorch later. For torch GPU build running on cpu only environment, we might be able to guard the prim import of nvfuser to disable it on those systems.
^^^ note that we are not doing this. Instead, we stick to linking against libnvrtc and driver directly. We are currently relying on pip installed libnvrtc on runtime system. #176

**Comment by jjsjann123** [comment]
Note that, I'm currently under the impression that there's some issue related to googletest with pip installed pytorch. (I don't yet know if the root-cause is from pytorch or googletest itself).
I'm still tracking that issue. I'll try to reach out to upstream for help.

**Comment by jjsjann123** [comment]
Opened an upstream issue on the googletest thing: https://github.com/pytorch/pytorch/issues/98093

**Comment by rdspring1** [comment]
Linking https://github.com/NVIDIA/Fuser/issues/126

We need to fix `CMAKE_PREFIX_INSTALL` to install files locally.

**Comment by rdspring1** [comment]
I've noticed when building with `python setup.py install` that `_C.cpython-39-x86_64-linux-gnu.so` is not installed with the first call. It will be added with subsequent calls.

**Comment by rdspring1** [comment]
Linking https://github.com/NVIDIA/Fuser/issues/152

**Comment by t-vi** [comment]
It seems that something fixed things for me (maybe `git clean -xfd`), I now get wheels. Thank you!

**Comment by jjsjann123** [comment]
since our current build has been in a somewhat acceptable manner. I have deprioritized this.

There's still a few items left for further improvements, but we don't need a sprint issue to track those. I'm closing this issue.
