### ISSUE TITLE
Options system overhaul

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#1994]
This issue is for a high-level discussion of the options system and how it interplays with the Python frontend and serde.

# Current status

To control options, we currently use the environment variables `NVFUSER_DISABLE` and `NVFUSER_ENABLE`, along with C++ enums `DisableOption` and `EnableOption`. In C++ code, we query whether these are enabled via e.g. `isOptionEnabled(EnableOption::KernelDb)`. The return value is dictated by global state in the form of vectors that track any non-default options that are currently enabled or disabled. That global state can also be modified using `EnableOptionsGuard` and `DisableOptionsGuard`; these use RAII to implement a stack of differing option sets.

# Problems with the current approach

**Options are ignored when caching**. By caching I am referring to all levels including `FusionCache`, `FusionExecutorCache`, and serde. If a Python user is given a mechanism to change options, they would reasonably expect to be able to run the same `FusionDefinition` twice with different options and receive different results. That is not the case: see https://github.com/NVIDIA/Fuser/pull/1905/files#diff-913efa62ae4ad7507c92a2044ebf9348aea148287cd7a752853412219b8cb2a4R3592-R3604 for an example.

Aside from that main limitation, the current approach is unhygienic as it requires managing global state, leading to subtle gotchas in parallel compilation like #1950. We should strive to limit the amount of global state we require.

# Desired elements of a new approach

*Note that I am calling them "features" below to distinguish from our current "options" system.*

1. We should be able to use features as cache keys. This should only apply to features that affect the generated CUDA code, not execution features like `NVFUSER_DISABLE=nvtx`.
2. The user should not need to know details about our implementation. For example they should not need to think about whether a feature is default enabled or not or whether it affects compilation or execution in order to enable it. Something like `fd.execute(inputs, disable='index_hoist')` should just work.
3. Features should survive a serde round-trip.
4. We should be able to cache the same fusion-inputs combination but with different features enabled and execute both as expected.

# Proposed approach

I suggest the following main changes to our options system. 

1. Instead of `EnableOption` and `DisableOption` being separate enums, we should unify these so that they are not organized based on their default behavior. This enables us to easily gather them into a thinly-wrapped `std::bitset` that summarizes all currently-enabled features.
5. `FusionDefinition.execute` should accept `enable=` and `disable=` kwonly args. These should be used to fill values in feature sets, falling back to env vars or defaults, before calling `FusionExecutorCache::runFusionWithInputs`.
3. `FusionExecutorCache` should accept a feature set in `runFusionWithInputs`, falling back to environment variables then to default values.
5. `FusionExecutorCache` should use the feature set when generating an input ID and concretized kernel cache.
6. `FusionKernelRuntime` should accept a feature set in its constructor, and it should hold its value as a const attribute. `FusionExecutor` should do the same, and these should be directly referred to instead of using global state to determine whether features are enabled.
8. Serde code should be updated to include these new attributes.
9. (Optional) Instead of mixing compilation features with execution features, we could separate these into different enums. That lets us ignore features that don't affect the generated CUDA kernel in caching, such as `NVFUSER_DISABLE=nvtx`. This might not be important, as most features actually do affect the generated kernel, and treating all options that way just means we might recompile identical kernels a bit more often.

```[tasklist]
### Tasks
- [ ] Create `FeatureSet` enum and bitset wrapper/env-var inspection code with tests.
- [ ] Plumb `FeatureSet` through `FusionExecutorCache`
- [ ] Enable options in frontend (replace #1905)
```
