### ISSUE TITLE
Eliminate unresolved broadcasts

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#340]
While implementing concretization of dynamic resizes (#258), it occurred to me that we should handle this particular type of concretization more generally. The only reason resize is a dynamic operation is that the output might have an extent equal to 1. We currently mark `IterDomain`s with extent 1 as `Broadcast` so that they maintain the ability to broadcast when they're used in later expressions. However, we don't actually check that they ever _are_ used this way. That means that if users pass inputs that sometimes have size one in some dimension (such as a batch or channel dimension) they will not be able to re-use kernels for size >1 even when that should be possible. In the short term, this also means that we cannot use `cat` along size-1 dimensions (#224).

One reason not to eliminate broadcasts too hastily is that one might add new expressions to the `Fusion` right up until the point that it's lowered. Even if we don't expect that to happen, until the concretization phase was introduced in #24 it was not clear at which point we even should attempt to clear out unresolved broadcasts.

Now that we have a concretization stage and will soon have an "initial info" building stage of concretization (#244), there is a natural place to put this analysis.

# Propagation of broadcast removal

When an `IterDomain`, `bS0`, with `IterType` equal to `Broadcast` is used in an operation in a position that aligns with another `IterDomain`, `iS1`, of type `Iteration`, we say that this "resolves" the broadcast `bS0`. This is an important event since it means we cannot use identical indexing for `iS1` and `bS0`, and we instead need to collapse the `iS1` index to 0 when using it in place of `bS0`. Note that `bS0` (or its `TensorView`) may appear in multiple `Expr`s, so there may be zero or multiple resolutions of a given broadcast.

If there are _zero_ resolutions of `bS0`, this means that any `Expr`s it appeared in contained other expressions that aligned perfectly; i.e. there either were no other expressions, they were unary, or other arguments also had broadcast `IterDomain`s in the aligned position. In this case, the behavior is no different from if the `IterType` of `bS0` had been `Iteration` to begin with.

## Aside: connecting the ID subgraph

To better facilitate analyzing broadcasts, it might be useful to explicitly connect the `IterDomain` subgraph of the `Fusion`. Note that of course the `Fusion` contains enough information to do the analysis as-is, but it is not very ergonomic. To see this, consider a simple unary op like `neg`. Consider the following `Fusion`:
```c++
  auto tv0 = makeConcreteTensor({3, 5});
  fusion->addInput(tv0);
  auto tv1 = makeConcreteTensor({3, 5});
  fusion->addInput(tv1);
  auto tv2 = mul(tv0, tv1);
  fusion->addOutput(tv2);
  fusion->printMath();
// Inputs:
//   T0_g[ iS0{3}, iS1{5} ], float
//   T1_g[ iS2{3}, iS3{5} ], float
// Outputs:
//   T2_g[ iS4{3}, iS5{5} ], float
  // The following all print 0
  std::cout << tv0->getMaybeRFactorDomain()[0]->uses().size() << std::endl;
  std::cout << tv0->getMaybeRFactorDomain()[1]->uses().size() << std::endl;
  std::cout << tv1->getMaybeRFactorDomain()[0]->uses().size() << std::endl;
  std::cout << tv1->getMaybeRFactorDomain()[1]->uses().size() << std::endl;
  std::cout << (void*)tv2->getRootDomain()[0]->definition() << std::endl;
  std::cout << (void*)tv2->getRootDomain()[1]->definition() << std::endl;
```
None of the `IterDomain`s are tracking uses or definitions, even though `iS4` and `iS5` are clearly derived from `[iS0, iS2]` and `[iS1, iS3]` respectively. I suggest we make this clear so that we can more easily inspect the actual dependencies between `IterDomain`.s To do this, we can introduce a new op type, tentatively called `Align` and a corresponding `align(std::vector<IterDomain*> ids, Expr* expr)` op. The `Align` op would hold the `ids` in its `inputs()` and it would hold a reference to the expression it appeared in as an attribute. We would modify `ops::newOutputTV` to use the `align` op to create new `IterDomain`s and assemble them into a `TensorDomain`, instead of using `IterDomainBuilder` directly as is done currently through `newOutputDomain`. With that change, the `Fusion` above would have two new `Align` expressions producing the IDs `iS4` and `iS5`, so that we could traverse from outputs to inputs without having to wind through the TV machinery (other than acquiring the output IDs in the first step).

Changing the `Fusion` by adding new `Expr`s runs the risk of winding up in an inconsistent state, so care must be taken when replacing `IterDomain`s that their history be preserved properly.

## Detecting unresolved `Broadcast` at concretization

After our current concretization is run (resolves all `Symbolic` IDs to `Broadcast` or `Iteration`), we would pass through all `Align` expressions to find broadcast resolutions. There is room for improvement here, but a naive algorithm would just mark each `Broadcast` input that is aligned with at least one concrete ID as "resolved". Then if an ID does not have any resolved `uses()`, it is safe to set it to type `Iteration`. This would automatically mark all output non-reduction IDs as `Iteration`. 

## Detecting unresolved `Broadcast` _before_ concretization

After we are comfortable eliminating broadcasts at concretization, we can push further to eliminate both broadcasts as well as symbolic IDs before we receive inputs. We can do this in much the same way as we do at concretization, but we need to be careful when handling `Symbolic` inputs. However, for example, if we have `Symbolic` IDs that only appear in unary ops before appearing in an output, these can safely be set to `Iteration`. Similarly, we can often reason about the equality of extents before we have concrete inputs (moreso once we address #320), and if we can prove equality of extents then we can prove an `Align` of `Symbolic` IDs is non-resolving, etc.

# Plan

I suggest that once #244 is merged, we add a stage that attempts to remove unresolved `Broadcast`s from the (still possibly dynamic) `Fusion`. Removing broadcasts would propagate upstream, since if there are no downstream broadcasts, we may also be able to change upstream `Symbolic` IDs to `Iteration`. Note that `Symbolic` is also used for `reshape`, but this should not interfere with concretization of `reshape`s since we already store the locations of dynamic reshapes when building concretization information, and we replace them during concretization; we should just be sure that IDs are connected properly by static reshape so that the graph is reconnected during concretization.

```[tasklist]
### Tasks
- [ ] Connect the IterDomain subgraph by introducing Align op
- [ ] Remove unresolved Broadcasts during concretization
- [ ] Remove unresolved symbolic branches before concretization
```
